name = "euserv2"
type = "javascript"
zone_id = ""
account_id = "18ed317776aedaf7754eed02a89d7294"
route = ""
workers_dev = true
kv_namespaces = [
         { binding = "Mydb", id = "18113596de6043aaaf9bd203df930d47" }
]
[triggers]
crons = ["59 23 * *  *", "0 */4 * * *"]
[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
