name = "euserv2"
type = "javascript"
zone_id = ""
account_id = "自己的地址"
route = ""
workers_dev = true
kv_namespaces = [
         { binding = "Mydb", id = "自己的地址" }
]
[triggers]
crons = ["59 23 * *  *", "0 */4 * * *"]
[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
